### PR TITLE
Fix various warning

### PR DESCRIPTION
**Pull request by sgn**

### CODE REVIEW

**Comment by jweyrich** [comment]
In the next line we overwrite the last byte of the buffer with `\0` to guarantee a NUL termination, but the compiler is analysing that call in specific without considering the next line, so the warning makes sense.
I believe we could just subtract 1 from the size passed to `strncpy` instead of changing the buffer size: `strncpy(packer_name, buff+1, packer_name_len-1);`

**Comment by sgn** [comment]
> I believe we could just subtract 1 from the size passed to `strncpy` instead of changing the buffer size: `strncpy(packer_name, buff+1, packer_name_len-1);`

Right, we don't need to increase buffer's size.

> Curiosity: Did this warning show up repeatedly? We use this last-byte-overwrite thing in various places.

I built with:

```sh
make prefix=/usr CFLAGS='-g -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe' LDFLAGS='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed '
```

after remove `/_FORTIFY_SOURCE/d` from `src/Makefile`.

No other warnings about `strncpy`.

There is 2 other warnings in `peres.c` that I didn't address, since I think they won't cause problems in real life. I'll leave it to you to decide :)

```
peres.c:487:60: warning: '%s' directive output may be truncated writing up to 255 bytes into a region of size between 156 and 255 [-Wformat-truncation=]
  487 |   snprintf(relativeFileName, sizeof(relativeFileName), "%s/%s%s",
      |                                                            ^~
  488 |    dirName,
  489 |    fileName,
      |    ~~~~~~~~
```
and
```
pesec.c:223:22: warning: variable 'input_fmt' set but not used [-Wunused-but-set-variable]
  223 |  const cert_format_e input_fmt = CERT_FORMAT_DER;
      |                      ^~~~~~~~~
```

**Comment by merces** [comment]
Hi @sgn, thanks for these comments and sorry about the delay!

We use `MAX_SIG_SIZE` to store the signature, not the packer name. The `packer_name` buffer is set to `MAX_MSG_SIZE` by intent. The biggest packer name in `userdb.txt` is 81 bytes long. 😉

Wrt your fixes, could you update this PR based on [this comment](https://github.com/merces/pev/pull/154#issuecomment-641996846)?

Thanks!

**Comment by merces** [comment]
Closed due to inactivity.

**Comment by sgn** [comment]
I was almost publishing an update :( Sorry for the delay.

**Comment by merces** [comment]
Oh, sorry about that @sgn. We thought you were not interested anymore. And we're sorry we take too long to get back to you. At this point reopening it seems to be impossible (I'm not really sure why). Would make sense to have  a new PR?

**Comment by sgn** [comment]
The email notification for this PR was lost in the middle of my mailbox.
I'll make new PR. Thanks. This time, it's a single change.

**Comment by merces** [comment]
Thank you very much!

**Pull request closed without merging**
